# generated by datamodel-codegen:
#   filename:  pet.json
#   timestamp: 2024-05-06T21:21:42+00:00

from __future__ import annotations

from typing import List

from pydantic import BaseModel
from robot.api.deco import keyword, library


class Category(BaseModel):
    id: int
    name: str


class Tag(BaseModel):
    id: int
    name: str


class Model(BaseModel):
    id: int
    category: Category
    name: str
    photoUrls: List[str]
    tags: List[Tag]
    status: str

@library
class petsLibrary:
    ROBOT_LIBRARY_SCOPE = "GLOBAL"
    
    @keyword
    def generate_add_new_pet_to_store_json(self, id, category, name, photoUrls, tags, status):
        model = Model(id=id, category=category, name=name, photoUrls=[photoUrls], tags=[tags], status=status)
        model = model.model_dump_json(indent=2)
        return model

